### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Kolkapetkinsyn** [MegaJoctan/MALE5#2]
Hi bro. Unfortunately, it was not possible to test your product. The library names in the examples are incorrect, and if you fix them, the code still throws an error.
![2024-02-09_18-30-57](https://github.com/MegaJoctan/MALE5/assets/86774928/bc181ffd-dd3d-4275-9b1c-35958a3d9070)
![2024-02-09_18-34-57](https://github.com/MegaJoctan/MALE5/assets/86774928/fa22d1a8-d4c0-49d2-933e-8ffe352e1ebb)
Please share working code examples

**Comment by MegaJoctan** [comment]
In the version 2.0.0 linear regression vonstructor is not callable with parameters 

```MQL5
CLinearRegression lr;
```
Inside your trading functions

```MQL5
lr.fit(x, y); //To train the model
lr.predict(x); //To make predictions
```
