### ISSUE TITLE
'y' - parameter conversion not allowed

### ISSUE THREAD

**Issue by 21Data** [MegaJoctan/MALE5#8]
![Screenshot from 2024-11-10 21-38-39](https://github.com/user-attachments/assets/b34e0683-6819-48ad-b8c9-60ea292eb965)

**Comment by MegaJoctan** [comment]
There is a conflict in versions coming from Matrix extend. 

Replace the file MatrixExtend.mqh in v3.0.0 release with the one found In the main branch

https://github.com/MegaJoctan/MALE5/blob/MQL5-ML/MatrixExtend.mqh
